### PR TITLE
Myway

### PR DESCRIPTION
**Pull request by gsf**
Hey!

### CODE REVIEW

**Comment by caseycesari** [comment]
Nice! I like it. Could you bump the version? 0.0.4?

**Comment by gsf** [comment]
Highly opinionated code, as you know, so do with it what you will.

Oh you might want to make sure the stuff in test.js is running since you're counting on some async responses. But it totally works for now.

**Comment by caseycesari** [comment]
Yeah, it was hard to find a good template for a npm library. I like this simpler structure and getting rid of the self-invoking stuff.

**Comment by gsf** [comment]
I think you should bump the version if you think it's time to make a new release.

**Comment by gsf** [comment]
And probably 0.0.3. No need to pad this thing to prove its stability.

**Comment by caseycesari** [comment]
True, true.

**Pull request merged**
